###
GET {{hostname}}/blog HTTP/1.1
Content-Type: application/json

###
GET {{hostname}}/blog/-N8BzD66SkJ6gRj3DSSk HTTP/1.1
Content-Type: application/json

###
POST  {{hostname}}/blog HTTP/1.1
Content-Type: application/json

    {
    "title": "My first blog",
    "description": "This is my first blog"
    }

###
PUT {{hostname}}/blog/-N8C-D_9RpGo4g3mNi_y HTTP/1.1
Content-Type: application/json

    {
    "title": "My third blog",
    "description": "This is my third blog"
    }

### 
DELETE {{hostname}}/blog/-N8BzD66SkJ6gRj3DSSk HTTP/1.1
Content-Type: application/json